[package]
name = "irq_safety"
version = "0.1.1"
authors = ["Kevin Boos <kevinaboos@gmail.com>"]

description = "A series of utilities that can be used to safely protect objects used within an interrupt handler or other IRQ context."
keywords = ["no_std", "kernel", "interrupts", "irq", "x86", "x86_64", "amd64", "lock", "mutex"]
license = "MIT"

[dependencies]
x86 = "0.8.1"
spin = "0.4.5"

[features]
const_fn = []
default = ["const_fn"]